spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instrumentation?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
 
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

