spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instrumentation?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ******
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
 
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

external:
  api: http://worldtimeapi.org/api/timezone/Asia/Kolkata