spring:
  application:
    name: instrumentation
  datasource:
    url: jdbc:mysql://localhost:3306/instrumentation?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ******
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
 
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

tracing:
  url: http://localhost:4318/v1/traces

external:
  api: http://worldtimeapi.org/api/timezone/Asia/Kolkata 